version: '2'
services:
    myapp:
        build: .
        container_name: "myapp"
        environment:
            - PROJECT_ID=${PROJECT_ID}
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/backupagent.json
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=${DB_USER}
          - MONGODB_PASS=${DB_PWD}
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet