version: '2'
services:
    myapp:
        build: .
        container_name: "myapp"
        environment:
            - PROJECT_ID=${PROJECT_ID}
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/backupagent.json
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - SERVER_URL=mongodb
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=${DB_USER}
          - MONGODB_PASS=${DB_PWD}
          - MONGO_INITDB_DATABASE=dev_db
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

    mongoClientTemp:
        image: mongo:latest
        container_name: mongoClientTemp
        volumes:
            - ./deployment_scripts:/deployment_scripts
        command: 
            - /deployment_scripts/entrypoint_db.sh
        environment:
          - DB_USER=${DB_USER}
          - DB_PWD=${DB_PWD}
          - DB_NAME=dev_db
        links:
            - mongodb:mongodb
        #command: mongo --host mongodb --eval  "db.getSiblingDB('dev_db').createUser({user:'agent25', pwd:'agent25', roles:[{role:'readWrite',db:'dev_db'}]});"
        depends_on:
            - mongodb

    web:
        build: website
        ports:
            - 8000:80
        volumes:
            - .:/srv/agent25-web
        working_dir: /usr/src/app