version: '3'
services:
    chatbot:
        build: .
        container_name: "chatbot-full"
        environment:
            - PROJECT_ID=${PROJECT_ID}
            - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/backupagent.json
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - SERVER_URL=mongodb
            - DOCKER=TRUE
            - LOG=TRUE
        ports:
            - 8090:80
        links:
            - mongodb
        depends_on:
            - mongodb
        volumes:
            - ./logs:/usr/src/app/logs
    mongodb:
        image: mongo:latest
        container_name: "mongodb-full"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
            - MONGODB_USER=${DB_USER}
            - MONGODB_PASS=${DB_PWD}
        volumes:
            - mongodb:/data/db
        ports:
            - 27018:27017
        command: mongod --logpath=/dev/null

    mongoClientInitializer:
        image: mongo:latest
        container_name: mongoClientInitializer-full
        volumes:
            - ./scripts:/scripts
        command: 
            - /scripts/entrypoint_db.sh
        environment:
            - DB_USER=${DB_USER}
            - DB_PWD=${DB_PWD}
            - DB_NAME=prod_chatbot
        links:
            - mongodb:mongodb
        depends_on:
            - mongodb

    web:
        build:
            context: chatbot/web
            args: 
                - "REACT_APP_SERVER_URL=http://${SERVER_URL}/"
        ports:
            - 8100:80
        volumes:
            - .:/srv/chatbot-web
        working_dir: /usr/src/app

volumes:
    mongodb:
